name: re
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.1.7
  cloud_firestore: ^5.3.0
  google_fonts: ^6.2.1
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  google_sign_in: ^6.1.0
  font_awesome_flutter: ^10.6.0
  cached_network_image: ^3.2.0
  image_picker: ^0.8.7+5
  fluttertoast: ^8.0.8
  permission_handler: ^10.0.0
  url_launcher: ^6.0.12
  shared_preferences: ^2.3.5
  http: ^1.2.2
  firebase_storage: ^12.3.7
  image_cropper: ^9.0.0
  uuid: ^3.0.7





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
